---
name: Formatting

'on': [pull_request_target]

permissions: {}

jobs:
  formatting:
    name: PR formatting
    uses: alisw/ali-bot/.github/workflows/c++-code-formatting.yml@master
    secrets:
      alibuild_github_token: ${{ secrets.ALIBUILD_GITHUB_TOKEN }}
