---
channel: DplusToPiKPi
labels: # class labels, keep the right number of classes
  [
    Bkg, # check that the background class position in this list matches ID_BKG value in the script
    Prompt,
    Nonprompt
  ]
col_tag: &col_tag fOriginMcRec # name of the column containing the candidate label tag

prepare_samples:
  input:
    files: # list of input .root files
      [
        /home/abigot/HFStudies/ML/training_samples/HF_LHC22b1a_2P3PDstar_run_136451/AO2D_merged.root
      ]
    tree_name: O2hfcanddplite

preselections: null # null or list of selections (e.g. [fCpa > 0.95, fPt > 2]) linked by "&&" logic in the script
cols_to_remove: # list of columns to remove in the output, default entry is MC origin flag
  [
    *col_tag
  ]
filt_bkg_mass: "fM < 1.82 || (1.92 < fM && fM < 2.00)" # invariant mass sidebands for Bkg labeling

output:
  dirs: # list of paths of output directories (without trailing slash)
    [
      .
    ]
  tree_name: treeMLDplus # tree name in the output files
