// Copyright 2019-2020 CERN and copyright holders of ALICE O2.
// See https://alice-o2.web.cern.ch/copyright for details of the copyright holders.
// All rights not expressly granted are reserved.
//
// This software is distributed under the terms of the GNU General Public
// License v3 (GPL Version 3), copied verbatim in the file "COPYING".
//
// In applying this license CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

///
/// \brief Table definitions for hf jet substrucuture observables
///
/// \author Nima Zardoshti <nima.zardoshti@cern.ch>

#ifndef PWGJE_DATAMODEL_JETSUBSTRUCTURE_H_
#define PWGJE_DATAMODEL_JETSUBSTRUCTURE_H_

#include "PWGDQ/DataModel/ReducedInfoTables.h"
#include "PWGHF/DataModel/DerivedTables.h"
#include "PWGJE/DataModel/Jet.h" // IWYU pragma: keep
#include "PWGJE/DataModel/JetReducedData.h"
#include "PWGJE/DataModel/JetReducedDataDQ.h"

#include <Framework/ASoA.h>

#include <cmath>
#include <cstdint>
#include <vector>

namespace o2::aod
{

namespace jetcollision
{                                                    //!
DECLARE_SOA_COLUMN(PosZ, posZ, float);               //!
DECLARE_SOA_COLUMN(Centrality, centrality, float);   //!
DECLARE_SOA_COLUMN(EventSel, eventSel, uint8_t);     //!
DECLARE_SOA_COLUMN(EventWeight, eventWeight, float); //!
} // namespace jetcollision

namespace jetmccollision
{
DECLARE_SOA_COLUMN(PosZ, posZ, float);               //!
DECLARE_SOA_COLUMN(Accepted, accepted, uint64_t);    //!
DECLARE_SOA_COLUMN(Attempted, attempted, uint64_t);  //!
DECLARE_SOA_COLUMN(XsectGen, xsectGen, float);       //!
DECLARE_SOA_COLUMN(XsectErr, xsectErr, float);       //!
DECLARE_SOA_COLUMN(EventWeight, eventWeight, float); //!
} // namespace jetmccollision

namespace jetsubstructure
{                                                                                                   //!
DECLARE_SOA_COLUMN(EnergyMother, energyMother, std::vector<float>);                                 //!
DECLARE_SOA_COLUMN(PtLeading, ptLeading, std::vector<float>);                                       //!
DECLARE_SOA_COLUMN(PtSubLeading, ptSubLeading, std::vector<float>);                                 //!
DECLARE_SOA_COLUMN(Theta, theta, std::vector<float>);                                               //!
DECLARE_SOA_COLUMN(NSub2DR, nSub2DR, float);                                                        //!
DECLARE_SOA_COLUMN(NSub1, nSub1, float);                                                            //!
DECLARE_SOA_COLUMN(NSub2, nSub2, float);                                                            //!
DECLARE_SOA_COLUMN(PairJetPt, pairJetPt, std::vector<float>);                                       //!
DECLARE_SOA_COLUMN(PairJetEnergy, pairJetEnergy, std::vector<float>);                               //!
DECLARE_SOA_COLUMN(PairJetTheta, pairJetTheta, std::vector<float>);                                 //!
DECLARE_SOA_COLUMN(PairJetPerpCone1Pt, pairJetPerpCone1Pt, std::vector<float>);                     //!
DECLARE_SOA_COLUMN(PairJetPerpCone1Energy, pairJetPerpCone1Energy, std::vector<float>);             //!
DECLARE_SOA_COLUMN(PairJetPerpCone1Theta, pairJetPerpCone1Theta, std::vector<float>);               //!
DECLARE_SOA_COLUMN(PairPerpCone1PerpCone1Pt, pairPerpCone1PerpCone1Pt, std::vector<float>);         //!
DECLARE_SOA_COLUMN(PairPerpCone1PerpCone1Energy, pairPerpCone1PerpCone1Energy, std::vector<float>); //!
DECLARE_SOA_COLUMN(PairPerpCone1PerpCone1Theta, pairPerpCone1PerpCone1Theta, std::vector<float>);   //!
DECLARE_SOA_COLUMN(PairPerpCone1PerpCone2Pt, pairPerpCone1PerpCone2Pt, std::vector<float>);         //!
DECLARE_SOA_COLUMN(PairPerpCone1PerpCone2Energy, pairPerpCone1PerpCone2Energy, std::vector<float>); //!
DECLARE_SOA_COLUMN(PairPerpCone1PerpCone2Theta, pairPerpCone1PerpCone2Theta, std::vector<float>);   //!
DECLARE_SOA_COLUMN(Angularity, angularity, float);                                                  //!
DECLARE_SOA_COLUMN(PtLeadingConstituent, ptLeadingConstituent, float);                              //!
DECLARE_SOA_COLUMN(PerpConeRho, perpConeRho, float);                                                //!
DECLARE_SOA_COLUMN(SplittingMatchingGeo, splittingMatchingGeo, std::vector<int>);                   //!
DECLARE_SOA_COLUMN(SplittingMatchingPt, splittingMatchingPt, std::vector<int>);                     //!
DECLARE_SOA_COLUMN(SplittingMatchingHF, splittingMatchingHF, std::vector<int>);                     //!
DECLARE_SOA_COLUMN(PairMatching, pairMatching, std::vector<int32_t>);                               //!
} // namespace jetsubstructure

namespace splitting
{                                                                                     //!
DECLARE_SOA_COLUMN(Pt, pt, float);                                                    //!
DECLARE_SOA_COLUMN(Eta, eta, float);                                                  //!
DECLARE_SOA_COLUMN(Phi, phi, float);                                                  //!
DECLARE_SOA_COLUMN(R, r, int);                                                        //!
DECLARE_SOA_COLUMN(SplittingMatchingGeo, splittingMatchingGeo, std::vector<int32_t>); //!
DECLARE_SOA_COLUMN(SplittingMatchingPt, splittingMatchingPt, std::vector<int32_t>);   //!
DECLARE_SOA_COLUMN(SplittingMatchingHF, splittingMatchingHF, std::vector<int32_t>);   //!
} // namespace splitting

// Defines the jet table definition
#define JETSPLITTING_TABLE_DEF(_jet_type_, _jet_description_, _name_, _track_type_, _cand_type_) \
                                                                                                 \
  namespace _name_##splitting                                                                    \
  {                                                                                              \
    DECLARE_SOA_INDEX_COLUMN(_jet_type_##Jet, jet);                                              \
  }                                                                                              \
  namespace _name_##splittingconstituents                                                        \
  {                                                                                              \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL(Tracks, tracks, int32_t, _track_type_, "_tracks");       \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL(Clusters, clusters, int32_t, JClusters, "_clusters");    \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL(Candidates, candidates, int32_t, _cand_type_, "_cand");  \
  }                                                                                              \
  DECLARE_SOA_TABLE(_jet_type_##SPs, "AOD", _jet_description_ "SP",                              \
                    o2::soa::Index<>,                                                            \
                    _name_##splitting::_jet_type_##JetId,                                        \
                    _name_##splittingconstituents::TracksIds,                                    \
                    _name_##splittingconstituents::ClustersIds,                                  \
                    _name_##splittingconstituents::CandidatesIds,                                \
                    splitting::Pt,                                                               \
                    splitting::Eta,                                                              \
                    splitting::Phi,                                                              \
                    splitting::R);

#define JETSPLITTINGMATCHING_TABLE_DEF(_jet_type_base_, _jet_type_tag_, _description_)             \
                                                                                                   \
  DECLARE_SOA_TABLE(_jet_type_base_##SPsMatchedTo##_jet_type_tag_##SPs, "AOD", _description_ "SP", \
                    splitting::SplittingMatchingGeo,                                               \
                    splitting::SplittingMatchingPt,                                                \
                    splitting::SplittingMatchingHF);

namespace pair
{                                                                     //!
DECLARE_SOA_COLUMN(PairMatching, pairMatching, std::vector<int32_t>); //!
} // namespace pair

// Defines the jet table definition
#define JETPAIR_TABLE_DEF(_jet_type_, _jet_description_, _name_, _track_type_, _cand_type_) \
                                                                                            \
  namespace _name_##pair                                                                    \
  {                                                                                         \
    DECLARE_SOA_INDEX_COLUMN(_jet_type_##Jet, jet);                                         \
  }                                                                                         \
  namespace _name_##pairconstituents                                                        \
  {                                                                                         \
    DECLARE_SOA_INDEX_COLUMN_FULL(Track1, track1, int32_t, _track_type_, "_track1");        \
    DECLARE_SOA_INDEX_COLUMN_FULL(Track2, track2, int32_t, _track_type_, "_track2");        \
    DECLARE_SOA_INDEX_COLUMN_FULL(Candidate1, candidate1, int32_t, _cand_type_, "_cand1");  \
    DECLARE_SOA_INDEX_COLUMN_FULL(Candidate2, candidate2, int32_t, _cand_type_, "_cand2");  \
  }                                                                                         \
  DECLARE_SOA_TABLE(_jet_type_##PRs, "AOD", _jet_description_ "PR",                         \
                    o2::soa::Index<>,                                                       \
                    _name_##pair::_jet_type_##JetId,                                        \
                    _name_##pairconstituents::Track1Id,                                     \
                    _name_##pairconstituents::Track2Id,                                     \
                    _name_##pairconstituents::Candidate1Id,                                 \
                    _name_##pairconstituents::Candidate2Id);

#define JETPAIRMATCHING_TABLE_DEF(_jet_type_base_, _jet_type_tag_, _description_)                  \
                                                                                                   \
  DECLARE_SOA_TABLE(_jet_type_base_##PRsMatchedTo##_jet_type_tag_##PRs, "AOD", _description_ "PR", \
                    pair::PairMatching);

namespace jetoutput
{
DECLARE_SOA_COLUMN(JetPt, jetPt, float);                     //!
DECLARE_SOA_COLUMN(JetPhi, jetPhi, float);                   //!
DECLARE_SOA_COLUMN(JetEta, jetEta, float);                   //!
DECLARE_SOA_COLUMN(JetY, jetY, float);                       //!
DECLARE_SOA_COLUMN(JetR, jetR, float);                       //!
DECLARE_SOA_COLUMN(JetArea, jetArea, float);                 //!
DECLARE_SOA_COLUMN(JetRho, jetRho, float);                   //!
DECLARE_SOA_COLUMN(JetPerpConeRho, jetPerpConeRho, float);   //!
DECLARE_SOA_COLUMN(JetNConstituents, jetNConstituents, int); //!
DECLARE_SOA_DYNAMIC_COLUMN(Pt, pt,                           //!
                           [](float jetPt) -> float { return jetPt; });
DECLARE_SOA_DYNAMIC_COLUMN(Phi, phi, //!
                           [](float jetPhi) -> float { return jetPhi; });
DECLARE_SOA_DYNAMIC_COLUMN(Eta, eta, //!
                           [](float jetEta) -> float { return jetEta; });
DECLARE_SOA_DYNAMIC_COLUMN(R, r, //!
                           [](float jetR) -> float { return jetR; });
} // namespace jetoutput

#define MCCOLL_TABLE_DEF(_jet_type_, _jet_description_, _name_)                                  \
  namespace _name_##mccollisionoutput                                                            \
  {                                                                                              \
    DECLARE_SOA_DYNAMIC_COLUMN(Dummy##_jet_type_, dummy##_jet_type_, []() -> int { return 0; }); \
  }                                                                                              \
  DECLARE_SOA_TABLE(_jet_type_##MCCOs, "AOD", _jet_description_ "MCCO",                          \
                    jetmccollision::PosZ,                                                        \
                    jetmccollision::Accepted,                                                    \
                    jetmccollision::Attempted,                                                   \
                    jetmccollision::XsectGen,                                                    \
                    jetmccollision::XsectErr,                                                    \
                    jetmccollision::EventWeight,                                                 \
                    _name_##mccollisionoutput::Dummy##_jet_type_<>);

// Defines the jet substrcuture table definition
#define JETSUBSTRUCTURE_TABLE_DEF(_jet_type_, _jet_description_, _name_, _cand_type_, _cand_description_, _jet_recoil_type_)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  namespace _name_##collisionoutput                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
  {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    DECLARE_SOA_DYNAMIC_COLUMN(Dummy##_jet_type_, dummy##_jet_type_, []() -> int { return 0; });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  DECLARE_SOA_TABLE(_jet_type_##COs, "AOD", _jet_description_ "CO", o2::soa::Index<>, jetcollision::PosZ, jetcollision::Centrality, jetcollision::EventSel, jetcollision::EventWeight, _name_##collisionoutput::Dummy##_jet_type_<>);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
  using _jet_type_##CO = _jet_type_##COs::iterator;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  namespace _name_##jetoutput                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \
  {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    DECLARE_SOA_INDEX_COLUMN_CUSTOM(_jet_type_##CO, collision, _jet_description_ "COs");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    DECLARE_SOA_INDEX_COLUMN_FULL_CUSTOM(Candidate, candidate, int, _cand_type_, _cand_description_ "S", "_0");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \
    DECLARE_SOA_INDEX_COLUMN(_jet_recoil_type_, jet);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
  }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
  DECLARE_SOA_TABLE(_jet_type_##Os, "AOD", _jet_description_ "O", o2::soa::Index<>, _name_##jetoutput::_jet_type_##COId, _name_##jetoutput::CandidateId, jetoutput::JetPt, jetoutput::JetPhi, jetoutput::JetEta, jetoutput::JetY, jetoutput::JetR, jetoutput::JetArea, jetoutput::JetRho, jetoutput::JetPerpConeRho, jetoutput::JetNConstituents);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
  DECLARE_SOA_TABLE(_jet_type_##Rs, "AOD", _jet_description_ "R", _name_##jetoutput::_jet_recoil_type_##Id, _name_##jetoutput::CandidateId, jetoutput::JetPt, jetoutput::JetPhi, jetoutput::JetEta, jetoutput::JetR, jetoutput::JetNConstituents, jetoutput::Pt<jetoutput::JetPt>, jetoutput::Phi<jetoutput::JetPhi>, jetoutput::Eta<jetoutput::JetEta>, jetoutput::R<jetoutput::JetR>);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
  DECLARE_SOA_TABLE(_jet_type_##ROs, "AOD", _jet_description_ "RO", o2::soa::Index<>, _name_##jetoutput::CandidateId, jetoutput::JetPt, jetoutput::JetPhi, jetoutput::JetEta, jetoutput::JetR, jetoutput::JetNConstituents);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
  using _jet_type_##O = _jet_type_##Os::iterator;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
  using _jet_type_##RO = _jet_type_##ROs::iterator;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
  namespace _name_##substructure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    DECLARE_SOA_INDEX_COLUMN_CUSTOM(_jet_type_##O, outputTable, _jet_description_ "Os");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    DECLARE_SOA_INDEX_COLUMN_CUSTOM(_jet_type_##RO, outputRecoilTable, _jet_description_ "ROs");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
    DECLARE_SOA_DYNAMIC_COLUMN(Dummy##_jet_type_, dummy##_jet_type_, []() -> int { return 0; });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  DECLARE_SOA_TABLE(_jet_type_##SSs, "AOD", _jet_description_ "SS", jetsubstructure::EnergyMother, jetsubstructure::PtLeading, jetsubstructure::PtSubLeading, jetsubstructure::Theta, jetsubstructure::NSub2DR, jetsubstructure::NSub1, jetsubstructure::NSub2, jetsubstructure::PairJetPt, jetsubstructure::PairJetEnergy, jetsubstructure::PairJetTheta, jetsubstructure::PairJetPerpCone1Pt, jetsubstructure::PairJetPerpCone1Energy, jetsubstructure::PairJetPerpCone1Theta, jetsubstructure::PairPerpCone1PerpCone1Pt, jetsubstructure::PairPerpCone1PerpCone1Energy, jetsubstructure::PairPerpCone1PerpCone1Theta, jetsubstructure::PairPerpCone1PerpCone2Pt, jetsubstructure::PairPerpCone1PerpCone2Energy, jetsubstructure::PairPerpCone1PerpCone2Theta, jetsubstructure::Angularity, jetsubstructure::PtLeadingConstituent, jetsubstructure::PerpConeRho, _name_##substructure::Dummy##_jet_type_<>);                                                                                                                   \
  DECLARE_SOA_TABLE(_jet_type_##SSOs, "AOD", _jet_description_ "SSO", _name_##substructure::_jet_type_##OId, jetsubstructure::EnergyMother, jetsubstructure::PtLeading, jetsubstructure::PtSubLeading, jetsubstructure::Theta, jetsubstructure::NSub2DR, jetsubstructure::NSub1, jetsubstructure::NSub2, jetsubstructure::PairJetPt, jetsubstructure::PairJetEnergy, jetsubstructure::PairJetTheta, jetsubstructure::PairJetPerpCone1Pt, jetsubstructure::PairJetPerpCone1Energy, jetsubstructure::PairJetPerpCone1Theta, jetsubstructure::PairPerpCone1PerpCone1Pt, jetsubstructure::PairPerpCone1PerpCone1Energy, jetsubstructure::PairPerpCone1PerpCone1Theta, jetsubstructure::PairPerpCone1PerpCone2Pt, jetsubstructure::PairPerpCone1PerpCone2Energy, jetsubstructure::PairPerpCone1PerpCone2Theta, jetsubstructure::Angularity, jetsubstructure::PtLeadingConstituent, jetsubstructure::SplittingMatchingGeo, jetsubstructure::SplittingMatchingPt, jetsubstructure::SplittingMatchingHF, jetsubstructure::PairMatching); \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  using _jet_type_##O = _jet_type_##Os::iterator;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
  using _jet_type_##SSO = _jet_type_##SSOs::iterator;

// define the mathcing table definition
#define JETMATCHING_TABLE_DEF(_jet_type_, _matched_jet_type_, _matched_jet_description_, _name_, _description_)                                                                                                                                      \
  namespace _name_##geomatched                                                                                                                                                                                                                       \
  {                                                                                                                                                                                                                                                  \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL_CUSTOM(_matched_jet_type_, matchedJetGeo, int32_t, _matched_jet_type_##Os, _matched_jet_description_ "Os", "_geo");                                                                                          \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL_CUSTOM(_matched_jet_type_##R, matchedJetGeo, int32_t, _matched_jet_type_##ROs, _matched_jet_description_ "ROs", "_geo");                                                                                     \
  }                                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                                     \
  namespace _name_##ptmatched                                                                                                                                                                                                                        \
  {                                                                                                                                                                                                                                                  \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL_CUSTOM(_matched_jet_type_, matchedJetPt, int32_t, _matched_jet_type_##Os, _matched_jet_description_ "Os", "_pt");                                                                                            \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL_CUSTOM(_matched_jet_type_##R, matchedJetPt, int32_t, _matched_jet_type_##ROs, _matched_jet_description_ "ROs", "_pt");                                                                                       \
  }                                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                                     \
  namespace _name_##candmatched                                                                                                                                                                                                                      \
  {                                                                                                                                                                                                                                                  \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL_CUSTOM(_matched_jet_type_, matchedJetCand, int32_t, _matched_jet_type_##Os, _matched_jet_description_ "Os", "_hf");                                                                                          \
    DECLARE_SOA_ARRAY_INDEX_COLUMN_FULL_CUSTOM(_matched_jet_type_##R, matchedJetCand, int32_t, _matched_jet_type_##ROs, _matched_jet_description_ "ROs", "_hf");                                                                                     \
  }                                                                                                                                                                                                                                                  \
  DECLARE_SOA_TABLE(_jet_type_##MOs, "AOD", _description_ "MO", _name_##substructure::_jet_type_##OId, _name_##geomatched::_matched_jet_type_##Ids, _name_##ptmatched::_matched_jet_type_##Ids, _name_##candmatched::_matched_jet_type_##Ids);       \
  using _jet_type_##MO = _jet_type_##MOs::iterator;                                                                                                                                                                                                  \
  DECLARE_SOA_TABLE(_jet_type_##RMOs, "AOD", _description_ "RMO", _name_##substructure::_jet_type_##ROId, _name_##geomatched::_matched_jet_type_##RIds, _name_##ptmatched::_matched_jet_type_##RIds, _name_##candmatched::_matched_jet_type_##RIds); \
  using _jet_type_##RMO = _jet_type_##RMOs::iterator;

#define JETSUBSTRUCTURE_TABLES_DEF(_jet_type_, _jet_description_, _jet_type_full_, _jet_full_description_, _track_type_data_, _cand_type_data_, _cand_description_data_, _track_type_ewsdata_, _cand_type_ewsdata_, _cand_description_ewsdata_, _track_type_mcd_, _cand_type_mcd_, _cand_description_mcd_, _particle_type_, _hfparticle_type_, _hfparticle_description_) \
  JETSUBSTRUCTURE_TABLE_DEF(_jet_type_##Jet, _jet_description_ "JET", _jet_type_##jet, _cand_type_data_, _cand_description_data_, ChargedJet)                                                                                                                                                                                                                            \
  JETSUBSTRUCTURE_TABLE_DEF(_jet_type_##EWSJet, _jet_description_ "EWSJET", _jet_type_##ewsjet, _cand_type_ewsdata_, _cand_description_ewsdata_, ChargedEventWiseSubtractedJet)                                                                                                                                                                                          \
  JETMATCHING_TABLE_DEF(_jet_type_##Jet, _jet_type_##EWSJet, _jet_description_ "EWSJET", _jet_type_##jet, _jet_description_ "JET")                                                                                                                                                                                                                                       \
  JETMATCHING_TABLE_DEF(_jet_type_##EWSJet, _jet_type_##Jet, _jet_description_ "JET", _jet_type_##ewsjet, _jet_description_ "EWSJET")                                                                                                                                                                                                                                    \
  JETSPLITTING_TABLE_DEF(_jet_type_full_, _jet_description_, _jet_full_description_, _track_type_data_, _cand_type_data_)                                                                                                                                                                                                                                                \
  JETSPLITTING_TABLE_DEF(_jet_type_full_##EventWiseSubtracted, _jet_description_ "EWS", _jet_full_description_##eventwisesubtracted, _cand_type_ewsdata_, _cand_type_ewsdata_)                                                                                                                                                                                           \
  JETSPLITTINGMATCHING_TABLE_DEF(_jet_type_full_, _jet_type_full_##EventWiseSubtracted, _jet_description_ "SP2EWS")                                                                                                                                                                                                                                                      \
  JETSPLITTINGMATCHING_TABLE_DEF(_jet_type_full_##EventWiseSubtracted, _jet_type_full_, _jet_description_ "EWSSP2")                                                                                                                                                                                                                                                      \
  JETPAIR_TABLE_DEF(_jet_type_full_, _jet_description_, _jet_full_description_, _track_type_data_, _cand_type_data_)                                                                                                                                                                                                                                                     \
  JETPAIR_TABLE_DEF(_jet_type_full_##EventWiseSubtracted, _jet_description_ "EWS", _jet_full_description_##eventwisesubtracted, _cand_type_ewsdata_, _cand_type_ewsdata_)                                                                                                                                                                                                \
  JETPAIRMATCHING_TABLE_DEF(_jet_type_full_, _jet_type_full_##EventWiseSubtracted, _jet_description_ "SP2EWS")                                                                                                                                                                                                                                                           \
  JETPAIRMATCHING_TABLE_DEF(_jet_type_full_##EventWiseSubtracted, _jet_type_full_, _jet_description_ "EWSSP2")                                                                                                                                                                                                                                                           \
  JETSUBSTRUCTURE_TABLE_DEF(_jet_type_##MCDJet, _jet_description_ "MCDJET", _jet_type_##mcdjet, _cand_type_mcd_, _cand_description_mcd_, ChargedMCDetectorLevelJet)                                                                                                                                                                                                      \
  JETSUBSTRUCTURE_TABLE_DEF(_jet_type_##MCPJet, _jet_description_ "MCPJET", _jet_type_##mcpjet, _hfparticle_type_, _hfparticle_description_, ChargedMCParticleLevelJet)                                                                                                                                                                                                  \
  MCCOLL_TABLE_DEF(_jet_type_##MCPJet, _jet_description_ "MCPJET", _jet_type_##mcpjet)                                                                                                                                                                                                                                                                                   \
  JETMATCHING_TABLE_DEF(_jet_type_##MCDJet, _jet_type_##MCPJet, _jet_description_ "MCPJET", _jet_type_##mcdjet, _jet_description_ "MCDJET")                                                                                                                                                                                                                              \
  JETMATCHING_TABLE_DEF(_jet_type_##MCPJet, _jet_type_##MCDJet, _jet_description_ "MCDJET", _jet_type_##mcpjet, _jet_description_ "MCPJET")                                                                                                                                                                                                                              \
  JETSPLITTING_TABLE_DEF(_jet_type_full_##MCDetectorLevel, _jet_description_ "D", _jet_full_description_##mcdetectorlevel, _track_type_mcd_, _cand_type_mcd_)                                                                                                                                                                                                            \
  JETSPLITTING_TABLE_DEF(_jet_type_full_##MCParticleLevel, _jet_description_ "P", _jet_full_description_##mcparticlelevel, _particle_type_, _hfparticle_type_)                                                                                                                                                                                                           \
  JETSPLITTINGMATCHING_TABLE_DEF(_jet_type_full_##MCDetectorLevel, _jet_type_full_##MCParticleLevel, _jet_description_ "DSP2P")                                                                                                                                                                                                                                          \
  JETSPLITTINGMATCHING_TABLE_DEF(_jet_type_full_##MCParticleLevel, _jet_type_full_##MCDetectorLevel, _jet_description_ "PSP2D")                                                                                                                                                                                                                                          \
  JETPAIR_TABLE_DEF(_jet_type_full_##MCDetectorLevel, _jet_description_ "D", _jet_full_description_##mcdetectorlevel, _track_type_mcd_, _cand_type_mcd_)                                                                                                                                                                                                                 \
  JETPAIR_TABLE_DEF(_jet_type_full_##MCParticleLevel, _jet_description_ "P", _jet_full_description_##mcparticlelevel, _particle_type_, _hfparticle_type_)                                                                                                                                                                                                                \
  JETPAIRMATCHING_TABLE_DEF(_jet_type_full_##MCDetectorLevel, _jet_type_full_##MCParticleLevel, _jet_description_ "DSP2P")                                                                                                                                                                                                                                               \
  JETPAIRMATCHING_TABLE_DEF(_jet_type_full_##MCParticleLevel, _jet_type_full_##MCDetectorLevel, _jet_description_ "PSP2D")

JETSUBSTRUCTURE_TABLES_DEF(C, "C", Charged, charged, JTracks, CJetCOs, "CJETCO", JTrackSubs, CEWSJetCOs, "CEWSJETCO", JTracks, CMCDJetCOs, "CMCDJETCO", JMcParticles, CMCPJetCOs, "CMCPJETCO");
JETSUBSTRUCTURE_TABLES_DEF(D0C, "D0C", D0Charged, d0charged, JTracks, HfD0Bases, "HFD0BASE", JTrackD0Subs, HfD0Bases, "HFD0BASE", JTracks, HfD0Bases, "HFD0BASE", JMcParticles, HfD0PBases, "HFD0PBASE");
JETSUBSTRUCTURE_TABLES_DEF(DplusC, "DPC", DplusCharged, dpluscharged, JTracks, HfDplusBases, "HFDPBASE", JTrackDplusSubs, HfDplusBases, "HFDPBASE", JTracks, HfDplusBases, "HFDPBASE", JMcParticles, HfDplusPBases, "HFDPPBASE");
JETSUBSTRUCTURE_TABLES_DEF(DsC, "DSC", DsCharged, dscharged, JTracks, HfDsBases, "HFDSBASE", JTrackDsSubs, HfDsBases, "HFDSBASE", JTracks, HfDsBases, "HFDSBASE", JMcParticles, HfDsPBases, "HFDSPBASE");
JETSUBSTRUCTURE_TABLES_DEF(DstarC, "DSTC", DstarCharged, dstarcharged, JTracks, HfDstarBases, "HFDSTBASE", JTrackDstarSubs, HfDstarBases, "HFDSTBASE", JTracks, HfDstarBases, "HFDSTBASE", JMcParticles, HfDstarPBases, "HFDSTPBASE");
JETSUBSTRUCTURE_TABLES_DEF(LcC, "LCC", LcCharged, lccharged, JTracks, HfLcBases, "HFLCBASE", JTrackLcSubs, HfLcBases, "HFLCBASE", JTracks, HfLcBases, "HFLCBASE", JMcParticles, HfLcPBases, "HFLCPBASE");
JETSUBSTRUCTURE_TABLES_DEF(B0C, "B0C", B0Charged, b0charged, JTracks, HfB0Bases, "HFB0BASE", JTrackB0Subs, HfB0Bases, "HFB0BASE", JTracks, HfB0Bases, "HFB0BASE", JMcParticles, HfB0PBases, "HFB0PBASE");
JETSUBSTRUCTURE_TABLES_DEF(BplusC, "BPC", BplusCharged, bpluscharged, JTracks, HfBplusBases, "HFBPBASE", JTrackBplusSubs, HfBplusBases, "HFBPBASE", JTracks, HfBplusBases, "HFBPBASE", JMcParticles, HfBplusPBases, "HFBPPBASE");
JETSUBSTRUCTURE_TABLES_DEF(XicToXiPiPiC, "XICXPPC", XicToXiPiPiCharged, xictoxipipicharged, JTracks, HfXicToXiPiPiBases, "HFXICXPPBASE", JTrackXicToXiPiPiSubs, HfXicToXiPiPiBases, "HFXICXPPBASE", JTracks, HfXicToXiPiPiBases, "HFXICXPPBASE", JMcParticles, HfXicToXiPiPiPBases, "HFXICXPPPBASE");
JETSUBSTRUCTURE_TABLES_DEF(DielectronC, "DIELC", DielectronCharged, dielectroncharged, JTracks, Dielectrons, "RTDIELECTRON", JTrackDielectronSubs, Dielectrons, "RTDIELECTRON", JTracks, Dielectrons, "RTDIELECTRON", JMcParticles, JDielectronMcs, "JDIELMC");

} // namespace o2::aod

#endif // PWGJE_DATAMODEL_JETSUBSTRUCTURE_H_
