# example config for cross section calculation of D+ mesons

observable: dsigmadpt # options: dsigmadpt, dNdpt
channel: DplustoKpipi # options: D0toKpi, DplustoKpipi, DstoKKpi, DstartoD0pi, LctopKpi, LctopK0S
system: pp # options: pp, pPb, PbPb
energy: 5TeV # options: 5TeV, 13TeV
period: Run2 # options: Run2

fraction: Nb # options: Nb, fc

FONLL: FONLLpred/DmesonLcPredictions_502TeV_y05_FFee_BRpythia8_SepContr_PDG2020.root

rawyield:
  filename: test/RawYields_Dplus_pp5TeV_prompt_central.root
  rawyieldhist: hRawYields
  normhist: hEvForNorm

acceff:
  filename: test/Eff_times_Acc_Dplus_pp5TeV_central_newAcc.root
  prompthist: hAccEffPrompt
  nonprompthist: hAccEffFD

output:
  directory: '.'
  filename: CrossSectionDplus_pp_5TeV # without extension
