/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef CB2PDF
#define CB2PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class CB2Pdf : public RooAbsPdf {
public:
  CB2Pdf() {} ;
  CB2Pdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _B,
        RooAbsReal& _C,
        RooAbsReal& _D,
        RooAbsReal& _E,
        RooAbsReal& _F);
  CB2Pdf(const CB2Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CB2Pdf(*this,newname); }
  inline virtual ~CB2Pdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy D ;
  RooRealProxy E ;
  RooRealProxy F ;

  Double_t evaluate() const ;

private:

  ClassDef(CB2Pdf,1) // Your description goes here...
};

#endif
