/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef GAUSPDF
#define GAUSPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class GausPdf : public RooAbsPdf {
public:
  GausPdf() {} ;
  GausPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  GausPdf(const GausPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new GausPdf(*this,newname); }
  inline virtual ~GausPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;

  Double_t evaluate() const ;

private:

  ClassDef(GausPdf,1) // Your description goes here...
};

#endif
