/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef VWGPDF
#define VWGPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class VWGPdf : public RooAbsPdf {
public:
  VWGPdf() {} ;
  VWGPdf(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _A,
	    RooAbsReal& _B,
        RooAbsReal& _C);
  VWGPdf(const VWGPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new VWGPdf(*this,newname); }
  inline virtual ~VWGPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;

  Double_t evaluate() const ;

private:

  ClassDef(VWGPdf,1) // Your description goes here...
};

#endif
